name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: sonarsource/sonarqube-scan-action@master
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache SonarQube dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Install SonarQube Scanner
        run: |
          curl -sL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip > sonar-scanner.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-4.6.2.2472-linux sonar-scanner
          export PATH=$PATH:$(pwd)/sonar-scanner/bin

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://your-sonarqube-server.com \
            -Dsonar.login=${{ secrets.SONAR_HOST_URL }}

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: sonar-report
          path: .scannerwork/report-task.txt
